name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ec2-13-126-63-148.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            # Load NVM (important for npm/node)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd ~

            # Clone or update repo
            if [ -d "CI-CD-Pipeline/.git" ]; then
              cd CI-CD-Pipeline
              git pull origin main
            else
              git clone https://github.com/lalitbgs2584-cell/CI-CD-Pipeline.git
              cd CI-CD-Pipeline
            fi

            # ðŸ”¥ Move into Next.js app directory
            cd ci-cd-test

            # Debug check
            pwd
            ls
            cat package.json

            # Install & build
            npm install
            npm run build

            # Start Next.js (port 3000)
            npm run start
