name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ec2-13-126-63-148.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            # create folder if not exists
            mkdir -p ~/my-app
            cd ~/my-app
            # clone if folder empty, else pull latest
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/lalitbgs2584-cell/CI-CD-Pipeline/ .
            fi
            # install dependencies and restart app
            npm install
            pm2 restart app || pm2 start index.js --name app
