name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ec2-13-126-63-148.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            # 1️⃣ Load nvm for Node/npm/pm2
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # 2️⃣ Create folder if it doesn't exist
            mkdir -p ~/my-app
            cd ~/my-app

            # 3️⃣ Clone repo if empty, else pull latest
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/lalitbgs2584-cell/CI-CD-Pipeline/ .
            fi

            # 4️⃣ Install dependencies
            npm install

            # 5️⃣ Start or restart app with PM2
            pm2 restart app || pm2 start index.js --name app

            # 6️⃣ Save PM2 process list so it restarts on reboot
            pm2 save
