name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Deploy on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ec2-13-203-158-204.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            # Go to home directory
            cd ~

            # Clone or update repo
            if [ -d "CI-CD-Pipeline/.git" ]; then
              cd CI-CD-Pipeline
              git reset --hard
              git pull origin main
            else
              git clone https://github.com/lalitbgs2584-cell/CI-CD-Pipeline.git
              cd CI-CD-Pipeline
            fi

            # Go into Next.js app
            cd ci-cd-test

            # Install dependencies & build app using full path to npm
            /home/ubuntu/.nvm/versions/node/v22.22.0/bin/npm ci
            /home/ubuntu/.nvm/versions/node/v22.22.0/bin/npm run build

            # Kill old Next.js process (if any)
            pkill -f "next start" || true

            # Start app in background using nohup
            nohup /home/ubuntu/.nvm/versions/node/v22.22.0/bin/npm run start > app.log 2>&1 &
